### ISSUE TITLE
2015-11-04 10:03:39.116 InstaSwipe[2822:124119] Error extracting token (null)

### ISSUE THREAD

**Issue by patrickpeng2091** [edwinbosire/TinderGram#1]
2015-11-04 10:03:39.116 InstaSwipe[2822:124119] Error extracting token (null)

**Comment by edwinbosire** [comment]
This will usually happen if the authentication wasn't successful.

**Comment by patrickpeng2091** [comment]
Hi， @edwinbosire 
Where configuration?

**Comment by patrickpeng2091** [comment]
info.plist  

InstagramAppClientId and InstagramAppRedirectURL ?

dbdedf9dcff441789aff45fbbbde2a27
http://www.qushang.net

Changed , But, the same display。

**Comment by edwinbosire** [comment]
I get two "Error extracting token (null)" then the login succeeds. One thing to try would be in your instagram.com/developer account. Have a look at the image below.
![screen shot 2015-11-05 at 21 56 54](https://cloud.githubusercontent.com/assets/1116125/10983550/1b060f4a-840b-11e5-9c28-63b11f69445c.png)

**Comment by patrickpeng2091** [comment]
Thank you very much.

**Comment by edwinbosire** [comment]
@pengting Hope it solved your issue
